In [1]:
import pandas as pd 
pd.read_json("train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [1]:
#sql
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     - ------------------------------------- 0.5/11.9 MB 510.6 kB/s eta 0:00:23
     - ------------------------------------- 0.5/11.9 MB 510.6 kB/s eta 0:00:23
     - ------------------------------------- 0.5/11.9 MB 510.6 kB/s eta 0:00:23
     -- ------------------------------------ 0.8/11.9 MB 487.0 kB/s eta 0:00:23
     -- ------------------------------------ 0.8/11.9 MB 487.0 kB/s eta 0:00:23
     --- ----------------------------------- 1.0/11.9 MB 522.4 kB/s eta 0:00:21
     --- ----------------------------------- 1.0/11.9 MB 522.4 kB/s eta 0:00:21
     ---- ---------------------------------- 1.3/11.9 MB 544.5 kB/s eta 0:00:20
     ---- ---------------------------------- 1.3/11.9 MB 544.5 kB/s eta 0:00:20
     ----- --------------------------------- 1.6/11.9 MB 555.7 kB/s eta 0:00:19
     ------ -------------------------------- 1.8/11.9 MB 594.5 kB/s eta 0:00:17
     ------ -------------------------------- 1.8/11.9 MB 594.5 kB/s eta 0:00:17
     ------ -------------------------------- 2.1/11.9 MB 596.6 kB/s eta 0:00:17
     ------ -------------------------------- 2.1/11.9 MB 596.6 kB/s eta 0:00:17
     ------ -------------------------------- 2.1/11.9 MB 596.6 kB/s eta 0:00:17
     ------- ------------------------------- 2.4/11.9 MB 594.4 kB/s eta 0:00:16
     -------- ------------------------------ 2.6/11.9 MB 604.4 kB/s eta 0:00:16
     -------- ------------------------------ 2.6/11.9 MB 604.4 kB/s eta 0:00:16
     --------- ----------------------------- 2.9/11.9 MB 620.5 kB/s eta 0:00:15
     ---------- ---------------------------- 3.1/11.9 MB 641.8 kB/s eta 0:00:14
     ---------- ---------------------------- 3.1/11.9 MB 641.8 kB/s eta 0:00:14
     ----------- --------------------------- 3.4/11.9 MB 658.4 kB/s eta 0:00:13
     ------------ -------------------------- 3.7/11.9 MB 674.5 kB/s eta 0:00:13
     ------------ -------------------------- 3.9/11.9 MB 689.7 kB/s eta 0:00:12
     ------------ -------------------------- 3.9/11.9 MB 689.7 kB/s eta 0:00:12
     ------------- ------------------------- 4.2/11.9 MB 698.0 kB/s eta 0:00:11
     -------------- ------------------------ 4.5/11.9 MB 708.8 kB/s eta 0:00:11
     --------------- ----------------------- 4.7/11.9 MB 721.4 kB/s eta 0:00:10
     --------------- ----------------------- 4.7/11.9 MB 721.4 kB/s eta 0:00:10
     ---------------- ---------------------- 5.0/11.9 MB 733.3 kB/s eta 0:00:10
     ----------------- --------------------- 5.2/11.9 MB 744.4 kB/s eta 0:00:09
     ------------------ -------------------- 5.5/11.9 MB 757.8 kB/s eta 0:00:09
     ------------------ -------------------- 5.8/11.9 MB 770.3 kB/s eta 0:00:08
     ------------------- ------------------- 6.0/11.9 MB 779.0 kB/s eta 0:00:08
     -------------------- ------------------ 6.3/11.9 MB 790.2 kB/s eta 0:00:08
     -------------------- ------------------ 6.3/11.9 MB 790.2 kB/s eta 0:00:08
     --------------------- ----------------- 6.6/11.9 MB 799.6 kB/s eta 0:00:07
     ---------------------- ---------------- 6.8/11.9 MB 808.5 kB/s eta 0:00:07
     ----------------------- --------------- 7.1/11.9 MB 817.0 kB/s eta 0:00:06
     ----------------------- --------------- 7.1/11.9 MB 817.0 kB/s eta 0:00:06
     ------------------------ -------------- 7.3/11.9 MB 806.7 kB/s eta 0:00:06
     ------------------------- ------------- 7.6/11.9 MB 817.7 kB/s eta 0:00:06
     ------------------------- ------------- 7.6/11.9 MB 817.7 kB/s eta 0:00:06
     ------------------------- ------------- 7.9/11.9 MB 818.2 kB/s eta 0:00:05
     -------------------------- ------------ 8.1/11.9 MB 818.6 kB/s eta 0:00:05
     -------------------------- ------------ 8.1/11.9 MB 818.6 kB/s eta 0:00:05
     --------------------------- ----------- 8.4/11.9 MB 820.1 kB/s eta 0:00:05
     ---------------------------- ---------- 8.7/11.9 MB 823.2 kB/s eta 0:00:04
     ----------------------------- --------- 8.9/11.9 MB 826.2 kB/s eta 0:00:04
     ----------------------------- --------- 8.9/11.9 MB 826.2 kB/s eta 0:00:04
     ------------------------------ -------- 9.2/11.9 MB 828.1 kB/s eta 0:00:04
     ------------------------------- ------- 9.4/11.9 MB 831.6 kB/s eta 0:00:03
     ------------------------------- ------- 9.7/11.9 MB 833.1 kB/s eta 0:00:03
     ------------------------------- ------- 9.7/11.9 MB 833.1 kB/s eta 0:00:03
     ------------------------------- ------ 10.0/11.9 MB 836.5 kB/s eta 0:00:03
     -------------------------------- ----- 10.2/11.9 MB 841.3 kB/s eta 0:00:02
     --------------------------------- ---- 10.5/11.9 MB 843.9 kB/s eta 0:00:02
     ---------------------------------- --- 10.7/11.9 MB 848.5 kB/s eta 0:00:02
     ----------------------------------- -- 11.0/11.9 MB 854.2 kB/s eta 0:00:01
     ----------------------------------- -- 11.0/11.9 MB 854.2 kB/s eta 0:00:01
     ------------------------------------ - 11.3/11.9 MB 859.6 kB/s eta 0:00:01
     ------------------------------------ - 11.5/11.9 MB 864.2 kB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 867.6 kB/s  0:00:14
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp314-cp314-win_amd64.whl size=248050 sha256=156c58bbe3f978d754797106655477179995c4949c42ee2ca578fe78385a6ea7
  Stored in directory: c:\users\lenovo\appdata\local\pip\cache\wheels\a2\5a\60\e03682d488f501428666827b000cfa0da00163afcd74ce2c14
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [2]:
import mysql.connector

In [4]:
conn=mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [6]:
import pandas as pd
pd.read_sql_query("SELECT * FROM city",conn)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15908\436916300.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city",conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [7]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND'",conn)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15908\1285320557.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND'",conn)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [10]:
df=pd.read_sql_query("SELECT * FROM country ",conn)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15908\1007524665.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("SELECT * FROM country ",conn)

In [11]:
df

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Koštunica,1792.0,YU
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [13]:
conn1=mysql.connector.connect(host='localhost',user='root',password='',database='chinook1')

In [14]:
import pandas as pd
pd.read_sql_query("SELECT * FROM invoice",conn1)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15908\2284177362.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM invoice",conn1)

,invoice_id,customer_id,invoice_date,billing_address,billing_city,billing_state,billing_country,billing_postal_code,total
0,1,2,2021-01-01,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,1.98
1,2,4,2021-01-02,Ullevålsveien 14,Oslo,NaN,Norway,0171,3.96
2,3,8,2021-01-03,Grétrystraat 63,Brussels,NaN,Belgium,1000,5.94
3,4,14,2021-01-06,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2021-01-11,69 Salem Street,Boston,MA,USA,2113,13.86
...,...,...,...,...,...,...,...,...,...
1231,1232,25,2025-12-05,319 N. Frances Street,Madison,WI,USA,53703,3.96
1232,1233,29,2025-12-06,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94
1233,1234,35,2025-12-09,"Rua dos Campeões Europeus de Viena, 4350",Porto,NaN,Portugal,NaN,8.91
1234,1235,44,2025-12-14,Porthaninkatu 9,Helsinki,NaN,Finland,00530,13.86
1235,1236,58,2025-12-22,"12,Community Centre",Delhi,NaN,India,110017,1.99